table Companies
	lineageTag: a54dd244-677f-4f63-9c62-e2cc151f05ef

	measure 'Joburi companie' = SUM(Companies[job_count])
		formatString: #,0
		lineageTag: 4fe4447c-fbc9-4545-8848-ec3953540f8e

	column company_id
		dataType: int64
		formatString: 0
		lineageTag: f7e85e8a-45ee-4755-b61b-3065cab0ec47
		summarizeBy: none
		sourceColumn: company_id

	column company_name
		dataType: string
		formatString: 0
		lineageTag: bb3f5fef-292b-479c-98a1-6378292a01bb
		summarizeBy: none
		sourceColumn: company_name

	column job_count
		dataType: int64
		formatString: 0
		lineageTag: 7936161f-654b-412b-8a76-5fe67cc68163
		summarizeBy: none
		sourceColumn: job_count

	partition Companies = m
		mode: import
		source =
				let
				 Snapshot = #table({"company_id", "company_name", "job_count"}, {
				{116, "DEFCON AI", 2},
				{87, "Pinterest", 1},
				{68, "Printful", 1},
				{51, "Entefy", 3},
				{146, "Guidewire Software", 1},
				{52, "URUS Group", 2},
				{190, "micro1", 1},
				{162, "Be | Shaping the Future", 2},
				{132, "SS&C Technologies", 1},
				{176, "Hormel Foods", 1},
				{169, "Bridgenext", 1},
				{276, "Kate Worthington", 1},
				{92, "VT Markets", 1},
				{237, "Brompton Associates Pte Ltd", 1},
				{101, "Openwave", 1},
				{262, "Zensar", 2},
				{115, "Anzen", 1},
				{60, "Datavant", 3},
				{97, "lemon.io", 1},
				{238, "Ocwen Financial Corporation", 1},
				{112, "Anaplan", 1},
				{271, "Siegen HR Solutions, Inc.", 1},
				{156, "Peraton", 1},
				{59, "CareSource", 1},
				{268, "Tulane University", 1},
				{65, "DigiU Pty Ltd", 2},
				{227, "Wipfli", 1},
				{98, "BioCatch", 1},
				{173, "Sinch", 2},
				{73, "Children's Hospital of Philadelphia", 1},
				{261, "Odyssey Systems Consulting Group, Ltd.", 1},
				{11, "Bitwarden", 1},
				{42, "Rancho BioSciences", 1},
				{235, "Stryker", 1},
				{121, "Agero", 1},
				{88, "Green Dot Corporation", 1},
				{188, "Hatch Asia", 1},
				{119, "Alternative Payments", 1},
				{113, "Vianai Systems", 1},
				{40, "Sprout Social", 1},
				{279, "MR DIY Philippines", 1},
				{147, "Urrly", 1},
				{214, "Navitus Health Solutions", 1},
				{9, "NTT DATA Romania SA", 2},
				{79, "Indero", 1},
				{226, "KLDiscovery", 1},
				{48, "BRAHMA AI", 1},
				{26, "Stratera Technologies", 1},
				{187, "Tier One Technologies", 1},
				{85, "lastminute.com", 1},
				{72, "HII", 2},
				{281, "Catholic Relief Services", 1},
				{95, "Lucy Electric", 1},
				{57, "Swish Analytics", 1},
				{19, "Bertelsmann-Jobs", 1},
				{244, "Blue River Technology", 1},
				{160, "Lifelancer", 1},
				{259, "Valiant Solutions", 1},
				{232, "WIRE IT", 1},
				{21, "Code for America", 1},
				{131, "Vezér Group", 1},
				{3, "Sysco", 1},
				{212, "Cummins", 1},
				{37, "Circana", 1},
				{28, "Courtyard", 3},
				{204, "Deutsche Telekom", 1},
				{5, "P@thlion Staffing Inc.", 5},
				{171, "Granicus", 1},
				{255, "ARNVIND GROUP", 1},
				{165, "George Bernard Consulting", 8},
				{56, "mercor", 6},
				{151, "Zoox", 1},
				{91, "FinThrive", 1},
				{283, "Glens Falls Hospital", 1},
				{209, "Attain Finance", 1},
				{74, "Pearson", 1},
				{54, "Certify", 1},
				{4, "Photon", 4},
				{225, "TheHiveCareers", 1},
				{34, "Wonderlic", 1},
				{245, "Augintel", 1},
				{96, "Your Personal AI", 4},
				{83, "ICF", 2},
				{63, "Inizio Partners Corp", 2},
				{90, "Jobs for Humanity", 1},
				{10, "AgSource", 2},
				{105, "Crowdstrike", 1},
				{35, "Syneos Health India Private Limited", 2},
				{216, "eClerx", 1},
				{174, "RecruitNest Consulting", 1},
				{107, "Clariter", 1},
				{233, "Teleperformance", 1},
				{134, "Symbotic", 1},
				{86, "Scalian", 3},
				{39, "Rhythm Pharmaceuticals", 1},
				{168, "SSOE Group", 2},
				{163, "Akamai Technologies", 7},
				{93, "Boomering Inc", 1},
				{89, "Boosta", 1},
				{219, "Bridge Talent Management", 1},
				{175, "Jobskey Consultancy", 2},
				{50, "Lawrence Livermore National Laboratory", 1},
				{253, "Summa Linguae Technologies", 2},
				{14, "Tenet Healthcare", 1},
				{66, "Carrington", 3},
				{158, "TASQ Staffing Solutions", 19},
				{277, "Conduent", 1},
				{155, "Bausch Health US, LLC", 1},
				{133, "Burnett Therapeutic Services", 1},
				{2, "Mashreq", 4},
				{16, "VORKIS knows what employer wants", 1},
				{199, "Pomelo Care", 1},
				{62, "Credit Acceptance", 1},
				{123, "Experian", 1},
				{75, "Climate First Bank", 1},
				{128, "Sequoia Connect", 1},
				{126, "Dautom", 4},
				{194, "Harvard University", 1},
				{243, "JNB Exectant", 1},
				{166, "Argano", 1},
				{142, "CSC", 1},
				{41, "Vulcury", 5},
				{46, "Bjak", 3},
				{224, "EXL", 2},
				{157, "Logistics Management Institute", 2},
				{53, "Root, Inc.", 1},
				{32, "BeiGene", 1},
				{7, "Xperteez Technology", 5},
				{275, "Source A Rep Pty Ltd", 1},
				{183, "Wesco", 1},
				{100, "Coderio", 1},
				{136, "Agara", 3},
				{38, "Community Health Systems", 1},
				{150, "QVC", 1},
				{140, "Vana", 1},
				{139, "Chickasaw Nation Industries, Inc.", 1},
				{12, "Fragomen", 1},
				{78, "Keurig Dr Pepper", 1},
				{24, "Honeycomb", 2},
				{191, "Unravel Carbon Pte Ltd", 1},
				{217, "Molina Healthcare", 5},
				{159, "Legrand", 2},
				{25, "Hitachi", 1},
				{94, "Grupo Data", 1},
				{218, "Cedars-Sinai Medical Center", 2},
				{234, "OperationsArmy", 1},
				{211, "Deploy", 1},
				{256, "Edgewater Federal Solutions", 1},
				{177, "HealthEdge", 1},
				{20, "HSO Group B.V.", 1},
				{1, "Netflix", 9},
				{76, "Progressive GE", 1},
				{18, "Upstart", 10},
				{185, "CADMUS RESOURCES", 1},
				{64, "Pearl Homes", 1},
				{145, "Amplify", 1},
				{55, "Compass UOL", 1},
				{148, "The University of Chicago Medicine", 1},
				{27, "CACI International Inc", 1},
				{270, "FocusKPI", 1},
				{143, "Doximity", 1},
				{23, "OnHires", 3},
				{203, "Cytel", 1},
				{58, "Power Digital Marketing", 1},
				{228, "Evolution Sports Group", 1},
				{8, "Satoshi Solutions", 1}
				}),
				 Source = if UsePostgreSQL then PostgreSQL.Database("localhost:5433", "job_market_db", [Query="SELECT * FROM analytics.jobs_by_company", CreateNavigationProperties=false]) else Snapshot,
				 Typed = Table.TransformColumnTypes(Source, {{"company_id", Int64.Type}, {"company_name", type text}, {"job_count", Int64.Type}})
				in Typed

